name: Android Fastlane with Firebase App Distribution Workflow

on:
  pull_request:
    branches:
      - development
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'

      - name: Create placeholder .env.firebase
        run: echo "FIREBASE_CONFIG_PLACEHOLDER=true" > .env.firebase

      - name: Decode and place google-services.json
        run: |
          echo "${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}" | base64 --decode > android/app/google-services.json

      - name: Set up Firebase service account credentials
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}" > $HOME/firebase-service-account.json
          export GOOGLE_APPLICATION_CREDENTIALS="$HOME/firebase-service-account.json"

      - name: Install Dependencies
        run: flutter pub get

      - name: Clear Flutter Build Cache
        run: flutter clean

      - name: Generate localization files
        run: flutter gen-l10n

      - name: Build APK for Production
        run: flutter build apk --release

      - name: Distribute APK to Firebase
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          file: build/app/outputs/flutter-apk/app-release.apk
          groups: maintainers
          releaseNotes: "First GitHub Action Firebase Distribution"
          debug: true

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          debug: true
