name: CI
on:
  push:
    branches: feature/Test
  pull_request:
    branches: feature/Test

  workflow_dispatch:

  jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Firebase App Distribution
        uses: hasretsariyer/firebase-app-distribution-github-action@v1
        with:
          app_id: ${{secrets.FIREBASE_APP_ID}}
          firebase_token: ${{secrets.FIREBASE_CLI_TOKEN}}
          app_file: app-release.apk
          tester_groups: maintainers