name: Android Fastlane with Firebase App Distribution Workflow

on:
  pull_request:
    branches:
      - development
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Set up Flutter
#        uses: subosito/flutter-action@v2
#        with:
#          channel: 'stable'
#          flutter-version: '3.24.4'
#
#      - name: Set up JDK
#        uses: actions/setup-java@v3
#        with:
#          java-version: 17
#          distribution: temurin
#
#      - name: Install Dependencies
#        run: flutter pub get
#
#      - name: Clear Flutter Build Cache
#        run: flutter clean
#
#      - name: Build APK for Production
#        run: flutter build apk --release -v

      - name: Firebase App Distribution
        uses: hasretsariyer/firebase-app-distribution-github-action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          firebase_token: ${{ secrets.FIREBASE_TOKEN }}
          app_file: app-release.apk
          groups: maintainers
          releaseNotes: "First GitHub Action Firebase Distribution"
