name: Android Firebase App Distribution
on:
  pull_request:
    branches:
      - development
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Step 2: Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # Step 3: Debugging: List files to locate gradlew
      - name: List files
        run: ls -la
        working-directory: android # Update if necessary

      # Step 4: Grant execute permissions to gradlew
      - name: Grant execute permissions
        run: chmod +x ./gradlew
        working-directory: android # Update if necessary

      # Step 5: Build APK
      - name: Build APK
        run: ./gradlew assembleRelease
        working-directory: android # Update if necessary

      # Step 6: Upload APK to Firebase App Distribution
      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_CLI_TOKEN }}
          groups: maintainers
          file: android/app/build/outputs/apk/release/app-release.apk
